[package]
name = "naxio/card-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.4"

Comm = "sleitnick/comm@0.3.1"
Component = "sleitnick/component@2.4.6"
Signal = "sleitnick/signal@1.2.1"
Input = "sleitnick/input@2.1.1"
Silo = "sleitnick/silo@0.1.1"
TableUtil = "sleitnick/table-util@1.1.5"
Trove = "sleitnick/trove@0.5.0"
Ser = "sleitnick/ser@1.0.5"
Loader = "sleitnick/loader@2.0.0"
Knit = "sleitnick/knit@1.4.7"
Timer = "sleitnick/timer@^1"